name: Render documentation

# see https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner
# for artifact handling and SBOM: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

on:
  push:
  #pull_request: # Not necessary, as it is already been executed on push
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.7"
        cache: 'pip' # caching pip dependencies
    - name: print versions for debugging
      run: python --version ; pip --version ; whoami ; pwd
    - name: Install graphviz & default-jdk
      run: |
        sudo apt-get update
        sudo apt-get upgrade --yes
        sudo apt-get install graphviz default-jdk
        sudo apt-get upgrade --yes
    - name: Install graphviz & default-jdk mini
      if: False
      run: |
        sudo apt-get install graphviz default-jdk
    - name: Install sphinx-needs from repo
      if: False
      run: |
        git clone https://github.com/useblocks/sphinx-needs.git ./sphinx_needs
        python -m pip install ./sphinx_needs/
    - name: Install dependencies
      run: |
        python -m pip install -r ./docs/requirements.txt
    - name: Lint the project with sphinx-lint
      if: False
      run: |
        sphinx-lint
    - name: Render the documentation
      run: >
        sphinx-build
        -b html ./docs ./public
        --jobs=auto
        --show-traceback
        --keep-going
        --fail-on-warning
    - name: Archive sphinx public folder
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-public
        path: |
          ./public/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Download sphinx public folder
        uses: actions/download-artifact@v4
        with:
          name: sphinx-public
          path: ./public/
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
